apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolistservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      containers:
        - name: js-app
          image: evgeniabzh/2dolist-app:latest
          ports:
            - containerPort: 8080
