name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js (якщо потрібен для обробки npm/yarn)
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies (якщо використовуєте npm або yarn)
        run: npm install
        working-directory: ./2dolist  # Правильний відступ

      - name: Build the app (якщо потрібна збірка)
        run: npm run build
        working-directory: ./2dolist  # Правильний відступ

      - name: Deploy (додайте ваші команди для розгортання)
        run: echo "Deployment step goes here"
