name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js (якщо потрібен для обробки npm/yarn)
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies (якщо використовуєте npm або yarn)
        run: npm install
        working-directory: ./

      - name: Build the app (якщо потрібна збірка)
        run: npm run build
        working-directory: ./

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 2dolist # Вкажіть тут ім'я вашого веб-додатка в Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
